[workstations]
192.168.56.111 ansible_user=erickalvarez

[web_servers]
192.168.56.105 ansible_user=erickalvarez
192.168.56.108 ansible_user=ealvarez

[db_servers]
192.168.56.107 ansible_user=erickalvarez

[file_servers]
192.168.56.108 ansible_user=ealvarez
 
[server1_lab]
192.168.56.120 ansible_user=alvarezworkstation

[server2_lab]
192.168.56.121 ansible_user=alvarezworkstation

[centos_lab]
192.168.56.122 ansible_user=ealvarez
